package alphachamados;

import Comando.dados;
import java.awt.Color;
import ConexaoBD.Conexao;
import ConexaoBD.MostrarTabela;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
/**
 *
 * @author Casa
 */
public class frmUsuario extends javax.swing.JFrame {
    Conexao cnx = new Conexao();


    int mural;
    /**
     * Creates new form frmUsuario
     */
    public frmUsuario() {
        initComponents();
        cnx.conecta();
        
        btnClick.doClick();
        
        setExtendedState(MAXIMIZED_BOTH);
        
        lblUsuario.setText(dados.getnome());
        
        pnlChamados.setVisible(false);
        pnlConfig.setVisible(false);
        
        try {
            cnx.executaSQL("select * from Usuarios where login_usuario = '"+dados.getlogin()+"' and senha = '"+dados.getsenha()+"'");
            
            cnx.rs.first();
            txtNome.setText(cnx.rs.getString("nome"));
            txtLogin.setText(cnx.rs.getString("login_usuario"));
            txtEmail.setText(cnx.rs.getString("email"));
            txtTelefone.setText(cnx.rs.getString("telefone"));
            pswSenha.setText(cnx.rs.getString("senha"));

            

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao localizar registro!" + ex.toString());
        }
        
        
        try {
            cnx.executaSQL("SELECT * FROM mural_avisos ORDER BY id_aviso DESC");

            if (!cnx.rs.next()) {
                txtAviso.setText("Ainda não tem Avisos");
                txtAvisoDesc.setText("");
            } else {
                cnx.rs.first();

                txtAviso.setText(cnx.rs.getString("nome_aviso"));
                txtAvisoDesc.setText(cnx.rs.getString("desc_aviso"));

            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao localizar registro!" + ex.toString());
        }
    }

       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMenu = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        btnSair = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        btnInicio = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        btnChamados = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        btnConfig = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        btnClick = new javax.swing.JButton();
        pnlPrincipal = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtAvisoDesc = new javax.swing.JTextArea();
        txtAviso = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        pnlConfig = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtNome = new javax.swing.JTextField();
        txtLogin = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        btnAtualizar = new javax.swing.JButton();
        pswSenha = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        pnlChamados = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        btnSolucionados = new javax.swing.JButton();
        btnTodos = new javax.swing.JButton();
        btnPendentes = new javax.swing.JButton();
        btnTodos1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Usuário");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMenu.setBackground(new java.awt.Color(255, 255, 255));
        pnlMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 228, 228)));
        pnlMenu.setForeground(new java.awt.Color(204, 204, 204));
        pnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logoPequeno.png"))); // NOI18N
        pnlMenu.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 40, 340, 150));

        btnSair.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnSair.setForeground(new java.awt.Color(153, 153, 153));
        btnSair.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSair.setText("Sair");
        btnSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSairMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSairMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSairMouseExited(evt);
            }
        });
        pnlMenu.add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 40, 30));

        jSeparator2.setForeground(new java.awt.Color(204, 204, 204));
        pnlMenu.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 300, 10));

        jSeparator3.setForeground(new java.awt.Color(204, 204, 204));
        pnlMenu.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 300, 10));

        jSeparator6.setForeground(new java.awt.Color(204, 204, 204));
        pnlMenu.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 690, 300, 10));

        jSeparator7.setForeground(new java.awt.Color(204, 204, 204));
        pnlMenu.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 750, 300, 10));

        btnInicio.setBackground(new java.awt.Color(255, 255, 255));
        btnInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInicioMouseClicked(evt);
            }
        });
        btnInicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 153, 153));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menu-home.png"))); // NOI18N
        jLabel13.setText(" Inicio");
        btnInicio.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 40));

        pnlMenu.add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 299, 60));

        btnChamados.setBackground(new java.awt.Color(255, 255, 255));
        btnChamados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChamados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnChamadosMouseClicked(evt);
            }
        });
        btnChamados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 153, 153));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menu-chamados.png"))); // NOI18N
        jLabel15.setText(" Meus chamados");
        btnChamados.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 40));

        pnlMenu.add(btnChamados, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 299, 60));

        btnConfig.setBackground(new java.awt.Color(255, 255, 255));
        btnConfig.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfig.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConfigMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnConfigMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnConfigMouseExited(evt);
            }
        });
        btnConfig.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 153, 153));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menu-configurações.png"))); // NOI18N
        jLabel12.setText(" Configurações");
        btnConfig.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 50));

        pnlMenu.add(btnConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 690, 299, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuario.png"))); // NOI18N
        pnlMenu.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        lblUsuario.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlMenu.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 100, 30));

        btnClick.setBorderPainted(false);
        btnClick.setContentAreaFilled(false);
        btnClick.setFocusPainted(false);
        btnClick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClickActionPerformed(evt);
            }
        });
        pnlMenu.add(btnClick, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 60, 30));

        getContentPane().add(pnlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 900));

        pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        pnlPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 142, 172));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Quadro");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, -1, -1));

        jLabel29.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("de avisos");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/mural.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, -1));

        pnlPrincipal.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 270));

        jPanel8.setBackground(new java.awt.Color(0, 178, 214));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtAvisoDesc.setEditable(false);
        txtAvisoDesc.setBackground(new java.awt.Color(0, 178, 214));
        txtAvisoDesc.setColumns(20);
        txtAvisoDesc.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtAvisoDesc.setForeground(new java.awt.Color(255, 255, 255));
        txtAvisoDesc.setLineWrap(true);
        txtAvisoDesc.setRows(5);
        txtAvisoDesc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jScrollPane8.setViewportView(txtAvisoDesc);

        jPanel8.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 470, 160));

        txtAviso.setEditable(false);
        txtAviso.setBackground(new java.awt.Color(0, 178, 214));
        txtAviso.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtAviso.setForeground(new java.awt.Color(255, 255, 255));
        txtAviso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel8.add(txtAviso, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 470, 50));

        jLabel51.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setText("Mural");
        jPanel8.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, -1, -1));

        jLabel47.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("Quadro de aviso");
        jPanel8.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, -1));

        pnlPrincipal.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 570, 500));

        getContentPane().add(pnlPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, -1, 900));

        pnlConfig.setBackground(new java.awt.Color(255, 255, 255));
        pnlConfig.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 142, 172));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Configuração");
        jPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, -1, -1));

        jLabel32.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("do Usuário");
        jPanel2.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/config.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, -1));

        pnlConfig.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 270));

        jPanel3.setBackground(new java.awt.Color(0, 178, 214));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNome.setBackground(new java.awt.Color(0, 178, 214));
        txtNome.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtNome.setForeground(new java.awt.Color(255, 255, 255));
        txtNome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtNome.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtNome.setEnabled(false);
        jPanel3.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 380, 40));

        txtLogin.setBackground(new java.awt.Color(0, 178, 214));
        txtLogin.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtLogin.setForeground(new java.awt.Color(255, 255, 255));
        txtLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtLogin.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtLogin.setEnabled(false);
        jPanel3.add(txtLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 380, 40));

        txtEmail.setBackground(new java.awt.Color(0, 178, 214));
        txtEmail.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtEmail.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtEmail.setEnabled(false);
        jPanel3.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 380, 40));

        txtTelefone.setBackground(new java.awt.Color(0, 178, 214));
        txtTelefone.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtTelefone.setForeground(new java.awt.Color(255, 255, 255));
        txtTelefone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtTelefone.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtTelefone.setEnabled(false);
        jPanel3.add(txtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 380, 40));

        btnAtualizar.setBackground(new java.awt.Color(255, 255, 255));
        btnAtualizar.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnAtualizar.setForeground(new java.awt.Color(0, 178, 214));
        btnAtualizar.setText("Atualizar");
        btnAtualizar.setBorder(null);
        btnAtualizar.setBorderPainted(false);
        btnAtualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });
        jPanel3.add(btnAtualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, 130, 50));

        pswSenha.setBackground(new java.awt.Color(0, 178, 214));
        pswSenha.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        pswSenha.setForeground(new java.awt.Color(255, 255, 255));
        pswSenha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        pswSenha.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        pswSenha.setEnabled(false);
        jPanel3.add(pswSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 380, 40));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Senha:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, 40));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nome:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 131, -1, 40));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Login:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, 40));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("E-mail:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, 40));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Telefone:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, 40));

        jLabel52.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(255, 255, 255));
        jLabel52.setText("Dados Pessoais");
        jPanel3.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        pnlConfig.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 560, 520));

        getContentPane().add(pnlConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 1140, 900));

        pnlChamados.setBackground(new java.awt.Color(242, 238, 238));
        pnlChamados.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlChamados.setMinimumSize(new java.awt.Dimension(1070, 445));
        pnlChamados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 142, 172));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Atendimento");
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, -1, -1));

        jLabel24.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Chamados");
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, -1, -1));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/atendimento.png"))); // NOI18N
        jPanel4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));

        btnSolucionados.setBackground(new java.awt.Color(0, 142, 172));
        btnSolucionados.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnSolucionados.setForeground(new java.awt.Color(255, 255, 255));
        btnSolucionados.setText("Solucionados");
        btnSolucionados.setBorder(null);
        btnSolucionados.setBorderPainted(false);
        btnSolucionados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSolucionados.setFocusPainted(false);
        btnSolucionados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolucionadosActionPerformed(evt);
            }
        });
        jPanel4.add(btnSolucionados, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, 160, 40));

        btnTodos.setBackground(new java.awt.Color(0, 115, 149));
        btnTodos.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnTodos.setForeground(new java.awt.Color(255, 255, 255));
        btnTodos.setText("Todos");
        btnTodos.setBorder(null);
        btnTodos.setBorderPainted(false);
        btnTodos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTodos.setFocusPainted(false);
        btnTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTodosActionPerformed(evt);
            }
        });
        jPanel4.add(btnTodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 160, 40));

        btnPendentes.setBackground(new java.awt.Color(0, 142, 172));
        btnPendentes.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnPendentes.setForeground(new java.awt.Color(255, 255, 255));
        btnPendentes.setText("Pendentes");
        btnPendentes.setBorder(null);
        btnPendentes.setBorderPainted(false);
        btnPendentes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPendentes.setFocusPainted(false);
        btnPendentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPendentesActionPerformed(evt);
            }
        });
        jPanel4.add(btnPendentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 160, 40));

        btnTodos1.setBackground(new java.awt.Color(0, 115, 149));
        btnTodos1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnTodos1.setForeground(new java.awt.Color(255, 255, 255));
        btnTodos1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/adicionar.png"))); // NOI18N
        btnTodos1.setText("Abrir");
        btnTodos1.setBorder(null);
        btnTodos1.setBorderPainted(false);
        btnTodos1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTodos1.setFocusPainted(false);
        btnTodos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTodos1ActionPerformed(evt);
            }
        });
        jPanel4.add(btnTodos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 100, 50));

        pnlChamados.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, -1));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setRowHeight(35);
        jScrollPane1.setViewportView(jTable1);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 1010));

        pnlChamados.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 1140, -1));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.setGridColor(new java.awt.Color(255, 255, 255));
        jTable2.setRowHeight(40);
        jScrollPane2.setViewportView(jTable2);

        jPanel6.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 1010));

        pnlChamados.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 1140, -1));

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable3.setGridColor(new java.awt.Color(255, 255, 255));
        jTable3.setRowHeight(40);
        jScrollPane3.setViewportView(jTable3);

        jPanel7.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 900));

        pnlChamados.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 1140, -1));

        getContentPane().add(pnlChamados, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 1140, 900));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseClicked
        frmLogin lg = new frmLogin();
        lg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSairMouseClicked

    private void btnSairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseEntered
        btnSair.setForeground(new Color(1, 174, 231));
    }//GEN-LAST:event_btnSairMouseEntered

    private void btnSairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseExited
        btnSair.setForeground(new Color(153, 153, 153));
    }//GEN-LAST:event_btnSairMouseExited

    private void btnInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioMouseClicked
        pnlPrincipal.setVisible(true);
        pnlChamados.setVisible(false);
        pnlConfig.setVisible(false);
    }//GEN-LAST:event_btnInicioMouseClicked

    private void btnChamadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChamadosMouseClicked
        pnlPrincipal.setVisible(false);
        pnlChamados.setVisible(true);
        pnlConfig.setVisible(false);
    }//GEN-LAST:event_btnChamadosMouseClicked

    private void btnConfigMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfigMouseClicked
        pnlPrincipal.setVisible(false);
        pnlChamados.setVisible(false);
        pnlConfig.setVisible(true);
    }//GEN-LAST:event_btnConfigMouseClicked

    private void btnConfigMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfigMouseEntered

    }//GEN-LAST:event_btnConfigMouseEntered

    private void btnConfigMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfigMouseExited

    }//GEN-LAST:event_btnConfigMouseExited

    private void btnSolucionadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolucionadosActionPerformed
        jPanel5.setVisible(false);
        jPanel6.setVisible(false);
        jPanel7.setVisible(true);

        btnTodos.setBackground(new Color(0, 142, 172));
        btnPendentes.setBackground(new Color(0, 142, 172));
        btnSolucionados.setBackground(new Color(0, 115, 149));
    }//GEN-LAST:event_btnSolucionadosActionPerformed

    private void btnTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTodosActionPerformed
        jPanel5.setVisible(true);
        jPanel6.setVisible(false);
        jPanel7.setVisible(false);

        btnTodos.setBackground(new Color(0, 115, 149));
        btnPendentes.setBackground(new Color(0, 142, 172));
        btnSolucionados.setBackground(new Color(0, 142, 172));
    }//GEN-LAST:event_btnTodosActionPerformed

    private void btnPendentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPendentesActionPerformed
        jPanel5.setVisible(false);
        jPanel6.setVisible(true);
        jPanel7.setVisible(false);

        btnTodos.setBackground(new Color(0, 142, 172));
        btnPendentes.setBackground(new Color(0, 115, 149));
        btnSolucionados.setBackground(new Color(0, 142, 172));
    }//GEN-LAST:event_btnPendentesActionPerformed

    private void btnTodos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTodos1ActionPerformed
        frmAbrirChamados ac = new frmAbrirChamados();
        ac.setVisible(true);
    }//GEN-LAST:event_btnTodos1ActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        frmAlterarUsuario fma = new frmAlterarUsuario();
        fma.setVisible(true);
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnClickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClickActionPerformed
        allChamados("SELECT c.id_chamado as ID, u.nome_unidade as 'Unidade', p.nome_problema as 'Problema', c.desc_problema as 'Descrição', c.nome_contato as 'Contato', c.ramal as 'Ramal', c.data_abertura as 'Abertura', s.nome_situacao as 'Situação' from chamados c\n"
            + "inner join unidades u on c.unidade = u.id_unidade \n"
            + "inner join situacoes s on c.situacao_chamado = s.id_situacao\n"
            + "inner join problemas p on c.tipo_problema = p.id_problema where nome_contato = '"+dados.getnome()+"'");
        pendentes("SELECT c.id_chamado as ID, u.nome_unidade as 'Unidade', p.nome_problema as 'Problema', c.desc_problema as 'Descrição', c.nome_contato as 'Contato', c.ramal as 'Ramal', c.data_abertura as 'Abertura', s.nome_situacao as 'Situação' from chamados c\n"
            + "inner join unidades u on c.unidade = u.id_unidade \n"
            + "inner join situacoes s on c.situacao_chamado = s.id_situacao\n"
            + "inner join problemas p on c.tipo_problema = p.id_problema where situacao_chamado=1 and nome_contato =  '"+dados.getnome()+"'");
        solucionados("SELECT c.id_chamado as ID, u.nome_unidade as 'Unidade', p.nome_problema as 'Problema', c.desc_problema as 'Descrição', c.nome_contato as 'Contato', c.ramal as 'Ramal', c.data_abertura as 'Abertura', s.nome_situacao as 'Situação' from chamados c\n"
            + "inner join unidades u on c.unidade = u.id_unidade \n"
            + "inner join situacoes s on c.situacao_chamado = s.id_situacao\n"
            + "inner join problemas p on c.tipo_problema = p.id_problema where situacao_chamado=2 and nome_contato = '"+dados.getnome()+"'");

    }//GEN-LAST:event_btnClickActionPerformed

    public void allChamados(String Sql) {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"ID", "Unidade", "Problema", "Descrição", "Contato", "Ramal", "Abertura", "Situação"};
        cnx.conecta();
        cnx.executaSQL(Sql);

        try {
            cnx.rs.first();
            do {
                dados.add(new Object[]{
                    cnx.rs.getString("ID"),
                    cnx.rs.getString("Unidade"),
                    cnx.rs.getString("Problema"),
                    cnx.rs.getString("Descrição"),
                    cnx.rs.getString("Contato"),
                    cnx.rs.getString("Ramal"),
                    cnx.rs.getString("Abertura"),
                    cnx.rs.getString("Situação")
                });
            } while (cnx.rs.next());
        } catch (SQLException ex) {
           // JOptionPane.showMessageDialog(rootPane, "Erro ao preencher o ARRAYLIST" + ex);
        }
        MostrarTabela tabela = new MostrarTabela(dados, colunas);
        jTable1.setModel(tabela);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(60);
        jTable1.getColumnModel().getColumn(0).setResizable(false);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(200);
        jTable1.getColumnModel().getColumn(1).setResizable(false);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(200);
        jTable1.getColumnModel().getColumn(2).setResizable(false);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(200);
        jTable1.getColumnModel().getColumn(3).setResizable(false);
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(150);
        jTable1.getColumnModel().getColumn(4).setResizable(false);
        jTable1.getColumnModel().getColumn(5).setPreferredWidth(60);
        jTable1.getColumnModel().getColumn(5).setResizable(false);
        jTable1.getColumnModel().getColumn(6).setPreferredWidth(120);
        jTable1.getColumnModel().getColumn(6).setResizable(false);
        jTable1.getColumnModel().getColumn(7).setPreferredWidth(130);
        jTable1.getColumnModel().getColumn(7).setResizable(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.setAutoResizeMode(jTable1.AUTO_RESIZE_OFF);
        jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    public void pendentes(String Sql) {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"ID", "Unidade", "Problema", "Descrição", "Contato", "Ramal", "Abertura", "Situação"};
        cnx.conecta();
        cnx.executaSQL(Sql);

        try {
            cnx.rs.first();
            do {
                dados.add(new Object[]{
                    cnx.rs.getString("ID"),
                    cnx.rs.getString("Unidade"),
                    cnx.rs.getString("Problema"),
                    cnx.rs.getString("Descrição"),
                    cnx.rs.getString("Contato"),
                    cnx.rs.getString("Ramal"),
                    cnx.rs.getString("Abertura"),
                    cnx.rs.getString("Situação")
                });
            } while (cnx.rs.next());
        } catch (SQLException ex) {
            //JOptionPane.showMessageDialog(rootPane, "Erro ao preencher o ARRAYLIST" + ex);
        }
        MostrarTabela tabela = new MostrarTabela(dados, colunas);
        jTable2.setModel(tabela);
        jTable2.getColumnModel().getColumn(0).setPreferredWidth(60);
        jTable2.getColumnModel().getColumn(0).setResizable(false);
        jTable2.getColumnModel().getColumn(1).setPreferredWidth(200);
        jTable2.getColumnModel().getColumn(1).setResizable(false);
        jTable2.getColumnModel().getColumn(2).setPreferredWidth(200);
        jTable2.getColumnModel().getColumn(2).setResizable(false);
        jTable2.getColumnModel().getColumn(3).setPreferredWidth(200);
        jTable2.getColumnModel().getColumn(3).setResizable(false);
        jTable2.getColumnModel().getColumn(4).setPreferredWidth(150);
        jTable2.getColumnModel().getColumn(4).setResizable(false);
        jTable2.getColumnModel().getColumn(5).setPreferredWidth(60);
        jTable2.getColumnModel().getColumn(5).setResizable(false);
        jTable2.getColumnModel().getColumn(6).setPreferredWidth(120);
        jTable2.getColumnModel().getColumn(6).setResizable(false);
        jTable2.getColumnModel().getColumn(7).setPreferredWidth(130);
        jTable2.getColumnModel().getColumn(7).setResizable(false);
        jTable2.getTableHeader().setReorderingAllowed(false);
        jTable2.setAutoResizeMode(jTable2.AUTO_RESIZE_OFF);
        jTable2.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }
    public void solucionados(String Sql) {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"ID", "Unidade", "Problema", "Descrição", "Contato", "Ramal", "Abertura", "Situação"};
        cnx.conecta();
        cnx.executaSQL(Sql);

        try {
            cnx.rs.first();
            do {
                dados.add(new Object[]{
                    cnx.rs.getString("ID"),
                    cnx.rs.getString("Unidade"),
                    cnx.rs.getString("Problema"),
                    cnx.rs.getString("Descrição"),
                    cnx.rs.getString("Contato"),
                    cnx.rs.getString("Ramal"),
                    cnx.rs.getString("Abertura"),
                    cnx.rs.getString("Situação")
                });
            } while (cnx.rs.next());
        } catch (SQLException ex) {
            //JOptionPane.showMessageDialog(rootPane, "Erro ao preencher o ARRAYLIST" + ex);
        }
        MostrarTabela tabela = new MostrarTabela(dados, colunas);
        jTable3.setModel(tabela);
        jTable3.getColumnModel().getColumn(0).setPreferredWidth(60);
        jTable3.getColumnModel().getColumn(0).setResizable(false);
        jTable3.getColumnModel().getColumn(1).setPreferredWidth(200);
        jTable3.getColumnModel().getColumn(1).setResizable(false);
        jTable3.getColumnModel().getColumn(2).setPreferredWidth(200);
        jTable3.getColumnModel().getColumn(2).setResizable(false);
        jTable3.getColumnModel().getColumn(3).setPreferredWidth(200);
        jTable3.getColumnModel().getColumn(3).setResizable(false);
        jTable3.getColumnModel().getColumn(4).setPreferredWidth(150);
        jTable3.getColumnModel().getColumn(4).setResizable(false);
        jTable3.getColumnModel().getColumn(5).setPreferredWidth(60);
        jTable3.getColumnModel().getColumn(5).setResizable(false);
        jTable3.getColumnModel().getColumn(6).setPreferredWidth(120);
        jTable3.getColumnModel().getColumn(6).setResizable(false);
        jTable3.getColumnModel().getColumn(7).setPreferredWidth(130);
        jTable3.getColumnModel().getColumn(7).setResizable(false);
        jTable3.getTableHeader().setReorderingAllowed(false);
        jTable3.setAutoResizeMode(jTable3.AUTO_RESIZE_OFF);
        jTable3.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows Classic".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JPanel btnChamados;
    public javax.swing.JButton btnClick;
    private javax.swing.JPanel btnConfig;
    private javax.swing.JPanel btnInicio;
    private javax.swing.JButton btnPendentes;
    private javax.swing.JLabel btnSair;
    private javax.swing.JButton btnSolucionados;
    private javax.swing.JButton btnTodos;
    private javax.swing.JButton btnTodos1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel pnlChamados;
    private javax.swing.JPanel pnlConfig;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPasswordField pswSenha;
    private javax.swing.JTextField txtAviso;
    private javax.swing.JTextArea txtAvisoDesc;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
